#-------------------------------------------------------------------------
# AUTHOR: your name
# FILENAME: title of the source file
# SPECIFICATION: description of the program
# FOR: CS 5990- Assignment #4
# TIME SPENT: how long it took you to complete the assignment
#-----------------------------------------------------------*/

#importing some Python libraries
from sklearn import tree
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

dbTraining = []
dbTest = []
X_training = []
y_training = []
classVotes = [] #this array will be used to count the votes of each classifier

#reading the training data from a csv file and populate dbTraining


train_df = pd.read_csv('optdigits.tra', sep=',', header=None)
dbTraining = train_df.to_numpy().tolist()

#reading the test data from a csv file and populate dbTest
test_df = pd.read_csv('optdigits.tes', sep=',', header=None)
dbTest = train_df.to_numpy().tolist()
#inititalizing the class votes for each test sample. Example: classVotes.append([0,0,0,0,0,0,0,0,0,0])
for i in dbTest:
    classVotes.append([0,0,0,0,0,0,0,0,0,0])

print("Started my base and ensemble classifier ...")

for k in range(20): #we will create 20 bootstrap samples here (k = 20). One classifier will be created for each bootstrap sample

    bootstrapSample = resample(dbTraining, n_samples=len(dbTraining), replace=True)

    #populate the values of X_training and y_training by using the bootstrapSample
    X_training = np.array(bootstrapSample)[:, :64]  # getting the first 64 fields to form the feature data for training
    y_training = np.array(bootstrapSample)[:, -1]  # getting the last field to form the class label for training

    #fitting the decision tree to the data
    clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth=None) #we will use a single decision tree without pruning it
    clf = clf.fit(X_training, y_training)

    for i, testSample in enumerate(dbTest):

        #make the classifier prediction for each test sample and update the corresponding index value in classVotes. For instance,
        # if your first base classifier predicted 2 for the first test sample, then classVotes[0,0,0,0,0,0,0,0,0,0] will change to classVotes[0,0,1,0,0,0,0,0,0,0].
        # Later, if your second base classifier predicted 3 for the first test sample, then classVotes[0,0,1,0,0,0,0,0,0,0] will change to classVotes[0,0,1,1,0,0,0,0,0,0]
        # Later, if your third base classifier predicted 3 for the first test sample, then classVotes[0,0,1,1,0,0,0,0,0,0] will change to classVotes[0,0,1,2,0,0,0,0,0,0]
        # this array will consolidate the votes of all classifier for all test samples
        pred = clf.predict([testSample[:-1]])[0]
        classVotes[i][pred] += 1

    if k == 0: #for only the first base classifier, compare the prediction with the true label of the test sample here to start calculating its accuracy
        corr = 0
        for sample in dbTest:
            pred = clf.predict([sample[:-1]])[0]
            if pred == sample[-1]:
                corr += 1
        accuracy = corr/len(dbTest)

    if k == 0: #for only the first base classifier, print its accuracy here
        print("Finished my base classifier (fast but relatively low accuracy) ...")
        print("My base classifier accuracy: " + str(accuracy))
        print("")

#now, compare the final ensemble prediction (majority vote in classVotes) for each test sample with the ground truth label to calculate the accuracy of the ensemble classifier (all base classifiers together)
corr = 0
for i, sam in enumerate(classVotes):
    max_value = max(sam)
    max_index = sam.index(max_value)
    if dbTest[i][-1] == max_index:
        corr += 1
accuracy = corr/len(dbTest)

#printing the ensemble accuracy here
print("Finished my ensemble classifier (slow but higher accuracy) ...")
print("My ensemble accuracy: " + str(accuracy))
print("")

print("Started Random Forest algorithm ...")

#Create a Random Forest Classifier
clf=RandomForestClassifier(n_estimators=20) #this is the number of decision trees that will be generated by Random Forest. The sample of the ensemble method used before

#Fit Random Forest to the training data
clf.fit(X_training, y_training)

#make the Random Forest prediction for each test sample. Example: class_predicted_rf = clf.predict([[3, 1, 2, 1, ...]]
corr=0
for sample in dbTest:
    pred = clf.predict([sample[:-1]])[0]
    if pred == sample[-1]:
        corr += 1
accuracy = corr/len(dbTest)
#printing Random Forest accuracy here
print("Random Forest accuracy: " + str(accuracy))

print("Finished Random Forest algorithm (much faster and higher accuracy!) ...")
